import { StyleSheet } from "react-native";

export const criarStyle = StyleSheet.create({
    container: {
        paddingVertical: 20,
        paddingHorizoltal: 20,
    },
    close: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#FD7509",
        position: "absolute",
        left: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#FD7509",
        textAlign: "center",
        marginBottom: 55,
    },
    subtitle: {
        fontSize: 16,
        marginLeft: 30,
        color: "#9b9b9b",
    },
    cardPublicacao: {
        backgroundColor: "#F5F3F4",
        borderColor: "#686666",
        borderWidth: 1,
        borderRadius: 8,
        width: "90%",
        height: 200,
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
        flexDirection: "column",
    },
    descricao: {
        fontSize: 16,
        color: "#9b9b9b",
        width: "100%",
        height: "100%",
        paddingLeft: 10,
        paddingTop: 10,
        textAlignVertical: "top",
    },
    caracteres: {
        fontSize: 16,
        color: "#9b9b9b",
        position: "absolute",
        bottom: 10,
        right: 10,
    },
    botoes: {
        color: "#9b9b9b",
        flexDirection: "row",
        alignItems: "center",
        marginTop: 10,
        marginLeft: 25,
    },
    colorText: {
        color: "#9b9b9b",
    },
    botaoImagem: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 10,
        marginLeft: 25,
    },
    botaoLocalizacao: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 10,
        marginLeft: 100,
    },
    containerBotaoPublicar: {
        marginTop: 25,
        width: "90%",
        alignSelf: "center",
    },
    previewImagem: {
        width: "70%",
        height: 250,
        borderRadius: 8,
        alignSelf: "center",
        marginTop: 10,
    },
    camaraControles: {
        flex: 1,
        justifyContent: "flex-end",
        alignItems: "center",
        paddingBottom: 40,
    },
    botaoFecharCamera: {
        position: "absolute",
        top: 50,
        left: 20,
    },
    botaoCapturar: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: "rgba(255,255,255,0.3)",
        justifyContent: "center",
        alignItems: "center",
    },
    circuloCapturar: {
        width: 58,
        height: 58,
        borderRadius: 29,
        backgroundColor: "#fff",
    },
    overlayOpcoes: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.4)",
        justifyContent: "flex-end",
    },
    menuOpcoes: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        paddingBottom: 30,
        paddingTop: 10,
    },
    itemOpcao: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 20,
        gap: 12,
    },
    textoItemOpcao: {
        fontSize: 16,
        color: "#000",
    },
    itemOpcaoCancelar: {
        paddingVertical: 16,
        paddingHorizontal: 20,
        alignItems: "center",
        marginTop: 5,
        borderTopWidth: 1,
        borderTopColor: "#eee",
    },
    textoCancelar: {
        fontSize: 16,
        color: "#FD7509",
        fontWeight: "bold",
    },
});